server:
  port: ${PORT:8080}
  address: 0.0.0.0
spring:
  application:
    name: outlier
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: ${JWT_SECRET}
  access-expiration: 900000
  refresh-expiration: 31536000000